### ISSUE TITLE
Add GIF & docs for DownloadAll

### ISSUE THREAD

**Issue by AasthaGithub** [AasthaGithub/Elemento#80]
**Type of issue/enquiry**
- Update Usage Part in docs(README) for DownloadAll functionality

**Description**
- [ ] Add steps to DownloadAll Selected elements
- [ ] Make & link DEMO GIF on the same 

 **Other Specifications**
- Steps to recreate: Go to Elements Page -> Check few elements -> Click Merge Button -> Click Download All Button<br>
Note: Setup .env & upload a few demo elements first. Contact if further help needed
- Hardware/software specification: Any

**Comment by chrysillala** [comment]
Hi, can I work on this as part of Hacktoberfest? Thanks!

**Comment by AasthaMehtaTech** [comment]
Hello Chrysilla, sure! go ahead, dm on aasthamehta2704@gmail.com for dummy data.
