### ISSUE TITLE
Create a report an issue endpoint using Github API v3

### ISSUE THREAD

**Issue by sarthakkundra** [AasthaGithub/Elemento#84]
**Feature Description**
Add an endpoint to the back-end api which takes in data and using the Github API v# opens an issue in the repository. 

**Problem it would solve**
This will be helpful so that people can report bugs or ask for new features

**Suggested Solution/ Changes**
- [ ] Add an endpoint to the API / Create new route file for Github

**Additional context**
This [documentation](https://developer.github.com/v3/issues/#create-an-issue) might help in achieving the required result.

**NOTE**
Attach screenshots HTTP requests and the respective results with the PR.

**Comment by DeadSpoon18** [comment]
I am not getting how to create auth token so that logged in user can create an issue and use github api, please help. `const express = require("express");
const fetch = require("node-fetch");
const app = express();
app.use(express.json({ extended: false }));

app.post("/createIssue", async (req, res) => {
  try {
    const url = "https://api.github.com/repos/abhinav972/githubtest/issues";
    const headers = {
        "Authorization" : `Token f7e3e1df34e90af073066c7afb43f989b3c2b5e4 `
    }
    const payLoad = {
      title: req.body.title,
      body: req.body.description,
    };
    const response = await fetch(url, {
      method: "POST",
      headers: headers,
      body: JSON.stringify(payLoad),
    });
    const result = await response.json();
    res.json(result);
  } catch (error) {
    console.log(error);
  }
});

app.listen(5000, () => {
  console.log("server started at port 5000");
});`
token i have used in header is personalized token that only i can use.

**Comment by AasthaGithub** [comment]
Prompt user to I/P his personal token whenever s/he wants to open an issue. Hope this answered your question.

**Comment by DeadSpoon18** [comment]
![issue](https://user-images.githubusercontent.com/58849158/94361896-327cb600-00d5-11eb-86c4-127af2befabe.png)
![issue2](https://user-images.githubusercontent.com/58849158/94361956-92735c80-00d5-11eb-99a3-cea82fafe8b9.png)
On client side the form takes title and body of the issue and git personal access token of the user.

**Comment by AasthaGithub** [comment]
Okay. Cool. Open PR when done.

**Comment by DeadSpoon18** [comment]
Can i open PR on 1st October as it will be useful for hacktoberfest.

**Comment by AasthaMehtaTech** [comment]
Solved by https://github.com/AasthaGithub/Elemento/pull/87
