### ISSUE TITLE
Create a report an issue modal

### ISSUE THREAD

**Issue by sarthakkundra** [AasthaGithub/Elemento#85]
**Feature Description**
Add a link in the footer which triggers a modal which has fields to create an issue in the repo. This modal will be connected with the endpoint being created to open new issues in the repo from the website.

**Problem it would solve**
This will help users report bugs easily and ask for new features.

**Suggested Solution/ Changes**
- [ ] Add a link in the footer.
- [ ] Trigger a modal opening on clicking the link.
- [ ] Add 3 fields inside it :- Name, description and checkbox between issue and feature

**Additional context**
This is the front-end for the following issue #84

**Comment by DeadSpoon18** [comment]
what will be endpoint i can use to open new issues or add feature ,that's the only part i can not understand.

**Comment by sarthakkundra** [comment]
@DeadSpoon18 the issue to create an endpoint is also open. It has not been done yet.

**Comment by Athira2199** [comment]
Would love to take up this issue could you please specify what is the pending section in the issue since I do see a merge being done.

**Comment by AasthaMehtaTech** [comment]
Endpoint creation has been done by the merged PR; while creating the report issue modal is left
(complete description in this issue description itself)
 @Athira2199

**Comment by Athira2199** [comment]
Got it would love to contribute. Will pull a PR once done. I believe by forking the master I am good to start.  
Will the github token field be automatically filled by the user ?
@AasthaGithub

**Comment by AasthaMehtaTech** [comment]
- Pleasure to hear your interest & will to contribute. Go ahead & feel free to ask any doubts here or in gitter channel of the repo.
- Github token could be cached into component states or added manually. No restrictions implementations wise. (One another way to ease this process for users is just taking their Github ID & redirecting to generating token or auto-generating(seeking permission) for that sake). 
- For getting started, forking would do, 
- Additionally, if you want to see the full-functionality (u need to generate MongoDB credentials & demo elements) DM on the mail id for further info of this.
